name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: xanderhendriks/action-build-stm32cubeide@v10.0
      with:
        project-path: '/'
    - name: make
      run: make
