name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get current date
      id: date
      run: |
        echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_STATE
    - uses: carlosperate/arm-none-eabi-gcc-action@v1
    - name: make
      run: make
    - name: Save production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: group-127-code-v${{ github.run_number }}-${{ env.date }}.bin
        path: build/group-127-code.bin
